export function Card({ title, subtitle, action, children, className = '', padded = true, onClick }) {
  return <section onClick={onClick} className={`bg-surface rounded-2xl border border-border shadow-[0_8px_28px_rgba(var(--shadow-color),.05)] ${onClick ? 'cursor-pointer hover:border-brand/40 transition-colors' : ''} ${className}`}>
    {title && <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 px-4 sm:px-5 py-4 border-b border-border-soft"><div><h3 className="text-[13.5px] font-bold text-ink-1">{title}</h3>{subtitle&&<p className="text-[11px] text-ink-3 mt-0.5">{subtitle}</p>}</div>{action}</div>}
    {padded && <div className={title?'px-4 sm:px-5 py-4 sm:py-5':'p-4 sm:p-5'}>{children}</div>}
  </section>;
}
const toneStyles={good:'bg-good-soft text-good border-good/25',warn:'bg-warn-soft text-warn border-warn/25',bad:'bg-bad-soft text-bad border-bad/25',neutral:'bg-surface-2 text-ink-2 border-border',brand:'bg-brand-soft text-brand border-brand/25'};
export function Pill({tone='neutral',children,className=''}){return <span className={`inline-flex items-center rounded-full border px-2.5 py-1 text-[10px] font-bold ${toneStyles[tone]} ${className}`}>{children}</span>}
export function StatTile({label,value,sublabel,tone}){return <div><p className="text-[11px] font-semibold uppercase tracking-wider text-ink-3">{label}</p><p className="text-[25px] sm:text-[29px] font-bold font-mono tabular-nums text-ink-1 mt-1">{value}</p>{sublabel&&<p className={`text-[11px] font-semibold mt-1 ${tone==='good'?'text-good':tone==='bad'?'text-bad':tone==='warn'?'text-warn':'text-ink-3'}`}>{sublabel}</p>}</div>}
export function EmptyState({icon:Icon,title,subtitle}){return <div className="py-14 text-center flex flex-col items-center"><div className="h-11 w-11 rounded-xl bg-surface-2 border border-border flex items-center justify-center text-brand mb-3">{Icon&&<Icon size={19}/>}</div><p className="text-sm font-bold text-ink-2">{title}</p>{subtitle&&<p className="text-xs text-ink-3 mt-1 max-w-sm">{subtitle}</p>}</div>}
