import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowUpRight, Brain, Database, GitCompareArrows, Users } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';
import PageHeader from '../components/PageHeader';
import { Card, Pill, StatTile } from '../components/ui';
import { useFootballData, qualityLabel, formatMatchTime } from '../data/footballData';

export default function Dashboard(){
  const {data,loading,error}=useFootballData();
  const distribution=useMemo(()=>{ if(!data) return []; const buckets=[['0–20',0],['20–40',0],['40–60',0],['60–80',0],['80–100',0]]; data.decisions.forEach(d=>{const v=d.actualValue; const i=v<20?0:v<40?1:v<60?2:v<80?3:4; buckets[i][1]++;}); return buckets.map(([bucket,count])=>({bucket,count,pct:data.decisions.length?Math.round(count/data.decisions.length*1000)/10:0}));},[data]);
  const stats=useMemo(()=>{if(!data)return null;const vals=data.decisions.map(d=>d.actualValue);const avg=vals.reduce((a,b)=>a+b,0)/(vals.length||1);const gaps=data.decisions.filter(d=>d.gap>0);const passes=data.actions.filter(a=>a.action==='pass').length;return {avg,gaps: gaps.length,passes};},[data]);
  const topPlayers=useMemo(()=>data?[...data.players].sort((a,b)=>b.avgValue-a.avgValue).slice(0,6):[],[data]);
  if(loading)return <Loading/>; if(error)return <Error text={error}/>;
  const teams=data.teams; const score=data.match.score;
  return <div className="max-w-[1500px] mx-auto">
    <PageHeader title="Match Overview" subtitle="Real event and counterfactual data from match 3857276 · 360° freeze-frame linked" action={<Link to="/decision-analysis" className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand text-white px-4 py-2.5 text-[12px] font-bold hover:bg-brand-strong"><GitCompareArrows size={15}/>Open Decision Analysis</Link>}/>
    <Card className="mb-5 overflow-hidden"><div className="bg-brand text-white p-5 sm:p-7"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[.18em] text-white/65">Analyzed fixture</p><p className="text-xl sm:text-2xl font-bold mt-1">{teams.join(' vs ')}</p><p className="text-xs text-white/65 mt-1">Match ID {data.match.id} · {data.match.possessions} possessions</p></div><div className="flex items-center gap-3"><div className="text-right"><p className="text-[10px] text-white/60">Score</p><p className="text-3xl font-bold font-mono tabular-nums">{score[teams[0]]||0}</p></div><span className="text-white/50">—</span><div><p className="text-[10px] text-white/60">&nbsp;</p><p className="text-3xl font-bold font-mono tabular-nums">{score[teams[1]]||0}</p></div></div></div></div>
      <div className="grid grid-cols-2 lg:grid-cols-4 divide-x divide-y lg:divide-y-0 divide-border-soft"><div className="p-4 sm:p-5"><StatTile label="Decision points" value={data.decisions.toLocaleString()} sublabel="Counterfactual-ready" tone="good"/></div><div className="p-4 sm:p-5"><StatTile label="360° linked actions" value={data.actions.toLocaleString()} sublabel="Tracked event records"/></div><div className="p-4 sm:p-5"><StatTile label="Average model value" value={stats.avg.toFixed(2)} sublabel="Across decision points"/></div><div className="p-4 sm:p-5"><StatTile label="Better alternatives" value={stats.gaps.toLocaleString()} sublabel={`${Math.round(stats.gaps/data.decisions.length*100)}% of decisions`} tone="warn"/></div></div>
    </Card>
    <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,1.3fr)_minmax(320px,.7fr)] gap-5">
      <Card title="Decision value distribution" subtitle="Actual decision value assigned by the trained model"><div className="h-[270px] sm:h-[310px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution} margin={{top:10,right:10,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" stroke="var(--border-soft)" vertical={false}/><XAxis dataKey="bucket" tick={{fill:'var(--ink-3)',fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'var(--ink-3)',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--border)',borderRadius:10,fontSize:12}} formatter={(v,n,p)=>[`${v} decisions`,p?.payload?.pct+'%']}/><Bar dataKey="count" fill="var(--brand)" radius={[6,6,0,0]} maxBarSize={54}/></BarChart></ResponsiveContainer></div></Card>
      <Card title="Top players" subtitle="Highest average decision value"><div className="space-y-1">{topPlayers.map((p,i)=><div key={p.name} className="flex items-center gap-3 rounded-xl px-2 py-2.5 hover:bg-surface-2"><span className="w-5 text-[11px] font-bold text-ink-3 font-mono">{i+1}</span><div className="h-9 w-9 rounded-full bg-brand-soft text-brand flex items-center justify-center text-[11px] font-bold">{p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="min-w-0 flex-1"><p className="text-[12.5px] font-bold truncate">{p.name}</p><p className="text-[10.5px] text-ink-3">{p.team} · {p.decisionCount} decisions</p></div><span className="font-mono font-bold text-[12px]">{p.avgValue.toFixed(2)}</span></div>)}</div><Link to="/player-analysis" className="mt-3 flex items-center justify-center gap-1.5 rounded-xl bg-surface-2 border border-border py-2.5 text-[11px] font-bold text-brand">Player analysis <ArrowUpRight size={13}/></Link></Card>
    </div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-5"><Mini icon={Database} label="Event records" value={data.actions.toLocaleString()}/><Mini icon={Activity} label="Passes" value={stats.passes.toLocaleString()}/><Mini icon={Users} label="Players tracked" value={data.players.length}/><Mini icon={Brain} label="Alternatives generated" value={data.decisions.reduce((n,d)=>n+d.candidates.length,0).toLocaleString()}/></div>
    <p className="text-[10.5px] text-ink-3 mt-5">Latest event: {formatMatchTime(data.actions.at(-1)?.timestamp)} · All figures on this page are calculated from the supplied JSON files.</p>
  </div>;
}
function Mini({icon:Icon,label,value}){return <div className="bg-surface border border-border rounded-xl p-4 flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-brand-soft text-brand flex items-center justify-center"><Icon size={16}/></div><div><p className="text-[10px] uppercase tracking-wider font-bold text-ink-3">{label}</p><p className="font-mono font-bold text-lg mt-0.5">{value}</p></div></div>}
function Loading(){return <div className="py-24 text-center text-ink-3">Loading match data…</div>}; function Error({text}){return <Card><p className="font-bold text-bad">Data load failed</p><p className="text-sm text-ink-3 mt-1">{text}</p></Card>}
